apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::586525008938:role/UdacityFlaskDeployCBKubectlRole
      username: build    
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::586525008938:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1L8Y1PMIVYXSU
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-20T20:49:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1911"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6bb960a8-1d2b-4929-9760-2b4d54b08460
